@extends('superadmin.layout')

@section('title', 'Invoice Details - {{ $invoice->invoice_number }}')

@section('content')
<div class="container-fluid px-2 py-0">
    <div class="d-flex justify-content-between align-items-center flex-wrap mb-2">
        <div>
            <h2 class="mb-0 border-0" style="color:#2c3e50;font-weight:600;">Invoice Details</h2>
            <p class="text-muted mb-2">Invoice Number: <strong>{{ $invoice->invoice_number }}</strong></p>
        </div>
        <div class="d-flex flex-wrap gap-2">
            <a href="{{ route('superadmin.invoices.index') }}" class="btn btn-primary">
                <i class="bi bi-arrow-left fs-6"></i> Back to Invoices
            </a>
            <a href="{{ route('superadmin.invoices.download', $invoice->id) }}" class="btn btn-success" target="_blank">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16" class="me-1">
                    <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                    <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
                </svg>
                Download PDF
            </a>
        </div>
    </div>
    <div class="accent-line"></div>

    <div class="row mt-4">
        <!-- Invoice Information -->
        <div class="col-md-8">
            <div class="card border-c-blue shadow-sm mb-4" style="border-radius: 16px;">
                <div class="card-header bg-primary text-white" style="border-radius: 16px 16px 0 0;">
                    <h5 class="mb-0">Invoice Information</h5>
                </div>
                <div class="card-body">
                    <div class="row app-details">
                        <div class="col-md-6">
                            <strong>Invoice Number:</strong>
                            <div>{{ $invoice->invoice_number }}</div>
                        </div>
                        <div class="col-md-6">
                            <strong>Application ID:</strong>
                            <div>
                                {{ $invoice->application->application_id }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <strong>Invoice Date:</strong>
                            <div>{{ $invoice->invoice_date->format('d M Y') }}</div>
                        </div>
                        <div class="col-md-6">
                            <strong>Due Date:</strong>
                            <div>
                                {{ $invoice->due_date->format('d M Y') }}
                                @if($invoice->due_date->isPast() && $invoice->status === 'pending')
                                    <span class="badge bg-danger ms-2">Overdue</span>
                                @endif
                            </div>
                        </div>
                        <div class="col-md-6">
                            <strong>Billing Period:</strong>
                            <div>{{ $invoice->billing_period ?? '—' }}</div>
                        </div>
                        <div class="col-md-6">
                            <strong>Status:</strong>
                            <div>
                                <span class="badge bg-secondary">{{ ucfirst($invoice->status) }}</span>
                            </div>
                        </div>
                        @if($invoice->generatedBy)
                        <div class="col-md-6">
                            <strong>Generated By:</strong>
                            <div>{{ $invoice->generatedBy->name }}</div>
                        </div>
                        @endif
                        @if($invoice->paid_at)
                        <div class="col-md-6">
                            <strong>Paid At:</strong>
                            <div>{{ $invoice->paid_at->format('d M Y, h:i A') }}</div>
                        </div>
                        @endif
                    </div>
                </div>
            </div>

            <!-- User Information -->
            <div class="card border-info shadow-sm mb-4" style="border-radius: 16px;">
                <div class="card-header bg-info text-white border-0" style="border-radius: 16px 16px 0 0;">
                    <h5 class="mb-0">User Information</h5>
                </div>
                <div class="card-body">
                    <div class="row app-details">
                        <div class="col-md-6">
                            <strong>Name:</strong>
                            <div>{{ $invoice->application->user->fullname }}</div>
                        </div>
                        <div class="col-md-6">
                            <strong>Email:</strong>
                            <div>{{ $invoice->application->user->email }}</div>
                        </div>
                        <div class="col-md-6">
                            <strong>Mobile:</strong>
                            <div>{{ $invoice->application->user->mobile }}</div>
                        </div>
                        <div class="col-md-6">
                            <strong>Registration ID:</strong>
                            <div>{{ $invoice->application->user->registrationid }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Amount Summary -->
        <div class="col-md-4">
            <div class="card border-success shadow-sm" style="border-radius: 16px;">
                <div class="card-header bg-success text-white" style="border-radius: 16px 16px 0 0;">
                    <h5 class="mb-0">Amount Summary</h5>
                </div>
                <div class="card-body">
                    <div class="mb-3">
                        <div class="d-flex justify-content-between mb-2 flex-wrap">
                            <span>Base Amount:</span>
                            <strong>₹{{ number_format($invoice->amount, 2) }}</strong>
                        </div>
                        <div class="d-flex justify-content-between mb-2 flex-wrap">
                            <span>GST Amount:</span>
                            <strong>₹{{ number_format($invoice->gst_amount, 2) }}</strong>
                        </div>
                        <hr>
                        <div class="d-flex justify-content-between flex-wrap">
                            <span><strong>Total Amount:</strong></span>
                            <strong style="font-size: 1.2em; color: #198754;">₹{{ number_format($invoice->total_amount, 2) }}</strong>
                        </div>
                    </div>
                    <div class="mt-3">
                        <strong>Currency:</strong> {{ $invoice->currency }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
